# Tracercoin Core — Windows NSIS installer script
# =================================================
# Reverse-engineered from litecoin-0.21.5.5-win64-setup.exe (Nullsoft/NSIS) and the
# canonical Bitcoin/Litecoin Core template share/setup.nsi.in. This is the resolved,
# Tracercoin-branded equivalent: every @autoconf@ variable is filled in and the
# hard-coded "Litecoin" leftovers from the template are corrected to Tracercoin.
#
# BUILD:
#   makensis tracercoin-setup.nsi
# Override the source/binary locations without editing this file:
#   makensis /DSRCDIR=C:\path\to\tracercoin-core /DRELEASE=C:\path\to\built\exes tracercoin-setup.nsi
#
# EXPECTED LAYOUT (matches what the Litecoin installer lays down):
#   ${RELEASE}\tracercoin-qt.exe            (GUI wallet, installed to $INSTDIR)
#   ${RELEASE}\tracercoind.exe              (daemon      -> $INSTDIR\daemon)
#   ${RELEASE}\tracercoin-cli.exe           (RPC client  -> $INSTDIR\daemon)
#   ${RELEASE}\tracercoin-tx.exe            (tx tool     -> $INSTDIR\daemon)
#   ${RELEASE}\tracercoin-wallet.exe        (wallet tool -> $INSTDIR\daemon)
#   ${SRCDIR}\COPYING                       (-> COPYING.txt)
#   ${SRCDIR}\doc\README_windows.txt        (-> readme.txt)
#   ${SRCDIR}\doc\*.*                        (-> $INSTDIR\doc, recursive)
#   ${SRCDIR}\share\pixmaps\{bitcoin.ico,nsis-wizard.bmp,nsis-header.bmp}
#     (branding art — swap these for Tracercoin artwork when ready)

# ---- configurable paths (override with makensis /D...) ----
!ifndef SRCDIR
  !define SRCDIR  "C:\XTKRecall\tracercoin-core"
!endif
!ifndef RELEASE
  !define RELEASE "${SRCDIR}\release"
!endif
!ifndef BRANDDIR
  !define BRANDDIR "C:\XTKRecall\tracercoin-installer\brand"
!endif

# ---- resolved package identity (was @PACKAGE_*@ etc. in setup.nsi.in) ----
!define PACKAGE_NAME     "Tracercoin Core"
!define PACKAGE_VERSION  "0.21.5.5"
!define PACKAGE_TARNAME  "tracercoin"
!define GUI_NAME         "tracercoin-qt"
!define DAEMON_NAME      "tracercoind"
!define CLI_NAME         "tracercoin-cli"
!define TX_NAME          "tracercoin-tx"
!define WALLET_TOOL_NAME "tracercoin-wallet"

Name "${PACKAGE_NAME} (64-bit)"

# Output installer name (override with makensis /DOUTFILE=...)
!ifndef OUTFILE
  !define OUTFILE "tracercoin-${PACKAGE_VERSION}-win64-setup.exe"
!endif
OutFile "${OUTFILE}"

RequestExecutionLevel highest
SetCompressor /SOLID lzma
SetDateSave off

# General Symbol Definitions
!define REGKEY  "SOFTWARE\$(^Name)"
!define COMPANY "${PACKAGE_NAME} project"
!define URL     "https://tracercoin.org/"

# MUI Symbol Definitions
# Branding art = Tracercoin (TFX) logo, generated by make-brand-art.py into ${BRANDDIR}.
!define MUI_ICON "${BRANDDIR}\tracercoin.ico"
!define MUI_WELCOMEFINISHPAGE_BITMAP "${BRANDDIR}\nsis-wizard.bmp"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_RIGHT
!define MUI_HEADERIMAGE_BITMAP "${BRANDDIR}\nsis-header.bmp"
!define MUI_FINISHPAGE_NOAUTOCLOSE
!define MUI_STARTMENUPAGE_REGISTRY_ROOT HKLM
!define MUI_STARTMENUPAGE_REGISTRY_KEY ${REGKEY}
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME StartMenuGroup
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "${PACKAGE_NAME}"
!define MUI_FINISHPAGE_RUN "$WINDIR\explorer.exe"
!define MUI_FINISHPAGE_RUN_PARAMETERS "$INSTDIR\${GUI_NAME}.exe"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"
!define MUI_UNWELCOMEFINISHPAGE_BITMAP "${BRANDDIR}\nsis-wizard.bmp"
!define MUI_UNFINISHPAGE_NOAUTOCLOSE

# Included files
!include Sections.nsh
!include MUI2.nsh
!include x64.nsh

# Variables
Var StartMenuGroup

# Installer pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_STARTMENU Application $StartMenuGroup
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

# Installer languages
!insertmacro MUI_LANGUAGE English

# Installer attributes
InstallDir "$PROGRAMFILES64\Tracercoin"
CRCCheck on
XPStyle on
BrandingText " "
ShowInstDetails show
VIProductVersion 0.21.5.5
VIAddVersionKey ProductName "${PACKAGE_NAME}"
VIAddVersionKey ProductVersion "${PACKAGE_VERSION}"
VIAddVersionKey CompanyName "${COMPANY}"
VIAddVersionKey CompanyWebsite "${URL}"
VIAddVersionKey FileVersion "${PACKAGE_VERSION}"
VIAddVersionKey FileDescription "Installer for ${PACKAGE_NAME}"
VIAddVersionKey LegalCopyright "Copyright (C) 2009-2026 The Tracercoin Core developers"
InstallDirRegKey HKCU "${REGKEY}" Path
ShowUninstDetails show

# Installer sections
Section -Main SEC0000
    SetOutPath $INSTDIR
    SetOverwrite on
    File "${RELEASE}\${GUI_NAME}.exe"
    File /oname=COPYING.txt "${SRCDIR}\COPYING"
    File /oname=readme.txt "${SRCDIR}\doc\README_windows.txt"
    SetOutPath $INSTDIR\daemon
    File "${RELEASE}\${DAEMON_NAME}.exe"
    File "${RELEASE}\${CLI_NAME}.exe"
    File "${RELEASE}\${TX_NAME}.exe"
    File "${RELEASE}\${WALLET_TOOL_NAME}.exe"
    SetOutPath $INSTDIR\doc
    File /r /x Makefile* "${SRCDIR}\doc\*.*"
    SetOutPath $INSTDIR
    WriteRegStr HKCU "${REGKEY}\Components" Main 1
SectionEnd

Section -post SEC0001
    WriteRegStr HKCU "${REGKEY}" Path $INSTDIR
    SetOutPath $INSTDIR
    WriteUninstaller $INSTDIR\uninstall.exe
    !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
    CreateDirectory $SMPROGRAMS\$StartMenuGroup
    CreateShortcut "$SMPROGRAMS\$StartMenuGroup\$(^Name).lnk" "$INSTDIR\${GUI_NAME}.exe"
    CreateShortcut "$SMPROGRAMS\$StartMenuGroup\${PACKAGE_NAME} (testnet, 64-bit).lnk" "$INSTDIR\${GUI_NAME}.exe" "-testnet" "$INSTDIR\${GUI_NAME}.exe" 1
    CreateShortcut "$SMPROGRAMS\$StartMenuGroup\Uninstall $(^Name).lnk" $INSTDIR\uninstall.exe
    !insertmacro MUI_STARTMENU_WRITE_END
    WriteRegStr HKCU "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayName "$(^Name)"
    WriteRegStr HKCU "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayVersion "${PACKAGE_VERSION}"
    WriteRegStr HKCU "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" Publisher "${COMPANY}"
    WriteRegStr HKCU "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" URLInfoAbout "${URL}"
    WriteRegStr HKCU "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayIcon "$INSTDIR\${GUI_NAME}.exe"
    WriteRegStr HKCU "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" UninstallString $INSTDIR\uninstall.exe
    WriteRegDWORD HKCU "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" NoModify 1
    WriteRegDWORD HKCU "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" NoRepair 1
    # tracercoin: URI protocol handler (was hard-coded "Litecoin" in the template)
    WriteRegStr HKCR "${PACKAGE_TARNAME}" "URL Protocol" ""
    WriteRegStr HKCR "${PACKAGE_TARNAME}" "" "URL:Tracercoin"
    WriteRegStr HKCR "${PACKAGE_TARNAME}\DefaultIcon" "" "$INSTDIR\${GUI_NAME}.exe"
    WriteRegStr HKCR "${PACKAGE_TARNAME}\shell\open\command" "" '"$INSTDIR\${GUI_NAME}.exe" "%1"'
SectionEnd

# Macro for selecting uninstaller sections
!macro SELECT_UNSECTION SECTION_NAME UNSECTION_ID
    Push $R0
    ReadRegStr $R0 HKCU "${REGKEY}\Components" "${SECTION_NAME}"
    StrCmp $R0 1 0 next${UNSECTION_ID}
    !insertmacro SelectSection "${UNSECTION_ID}"
    GoTo done${UNSECTION_ID}
next${UNSECTION_ID}:
    !insertmacro UnselectSection "${UNSECTION_ID}"
done${UNSECTION_ID}:
    Pop $R0
!macroend

# Uninstaller sections
Section /o -un.Main UNSEC0000
    Delete /REBOOTOK "$INSTDIR\${GUI_NAME}.exe"
    Delete /REBOOTOK $INSTDIR\COPYING.txt
    Delete /REBOOTOK $INSTDIR\readme.txt
    RMDir /r /REBOOTOK $INSTDIR\daemon
    RMDir /r /REBOOTOK $INSTDIR\doc
    DeleteRegValue HKCU "${REGKEY}\Components" Main
SectionEnd

Section -un.post UNSEC0001
    DeleteRegKey HKCU "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)"
    Delete /REBOOTOK "$SMPROGRAMS\$StartMenuGroup\Uninstall $(^Name).lnk"
    Delete /REBOOTOK "$SMPROGRAMS\$StartMenuGroup\$(^Name).lnk"
    Delete /REBOOTOK "$SMPROGRAMS\$StartMenuGroup\${PACKAGE_NAME} (testnet, 64-bit).lnk"
    Delete /REBOOTOK "$SMSTARTUP\Tracercoin.lnk"
    Delete /REBOOTOK $INSTDIR\uninstall.exe
    Delete /REBOOTOK $INSTDIR\debug.log
    Delete /REBOOTOK $INSTDIR\db.log
    DeleteRegValue HKCU "${REGKEY}" StartMenuGroup
    DeleteRegValue HKCU "${REGKEY}" Path
    DeleteRegKey /IfEmpty HKCU "${REGKEY}\Components"
    DeleteRegKey /IfEmpty HKCU "${REGKEY}"
    DeleteRegKey HKCR "${PACKAGE_TARNAME}"
    RmDir /REBOOTOK $SMPROGRAMS\$StartMenuGroup
    RmDir /REBOOTOK $INSTDIR
    Push $R0
    StrCpy $R0 $StartMenuGroup 1
    StrCmp $R0 ">" no_smgroup
no_smgroup:
    Pop $R0
SectionEnd

# Installer functions
Function .onInit
    InitPluginsDir
    ${If} ${RunningX64}
      ; disable registry redirection (enable access to 64-bit portion of registry)
      SetRegView 64
    ${Else}
      MessageBox MB_OK|MB_ICONSTOP "Cannot install 64-bit version on a 32-bit system."
      Abort
    ${EndIf}
FunctionEnd

# Uninstaller functions
Function un.onInit
    ReadRegStr $INSTDIR HKCU "${REGKEY}" Path
    !insertmacro MUI_STARTMENU_GETFOLDER Application $StartMenuGroup
    !insertmacro SELECT_UNSECTION Main ${UNSEC0000}
FunctionEnd
